:time_estimate: 5

= Lab: Publish a Bootc Container Image in a Private Container Registry

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Publish a system image in an OCI container registry and use it to perform system testing of edge devices.

WARNING: Work in progress

== PROVISORY OUTLINE

* Push a container and test the remote image with a local VM
* Tag a remote image to illustrate a promotion workflow.
* Use the remote image on a local VM (if it was possible to test images in VMs without first push to a remote container registry)
* Registry authentication at build time and at run/install time.


== Before you Begin

You need a _development machine_ running RHEL, to which you have access using an unprivileged user account.

You also need a _test machine_ running RHEL, to which you have unrestricted root access.

These instructions were tested on RHEL 10.0 but should work with minimal or no change on and newer and older RHEL releases, since 9.6.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`. If not, please adapt the instructions to your test environment.

Make sure you verified your test environment by following the xref:ch1-intro:s3-prereqs-lab.adoc[first lab] of this course.

== Instructions

You will publish a bootc container image in a private registry, in a way that emulates the results of a CI/CD pipeline, and you will reprovision an existing system from that container image, simulating one of the ways you could deploy bootc containers on actual edge devices.

1. Prepare to start this activity by checking that you have the outcomes from previous activities.

.. If needed, create a local clone of the sample code repository of this course, but do NOT enter its directory.
Stay on your home directory to start this lab.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *git clone https://github.com/RedHatQuickCourses/rhde-bootc-samples.git*
Cloning into 'rhde-bootc-samples'...
...
--
+
.. If needed, login to your private registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Verify that you have a bootc container image named `localhost/httpd-system` in your local container storage.
If you do not, please perform the xref:ch2-build:s2-podman-lab.adoc[previous lab] which builds that image.
+
[source,subs="verbatim,quotes"]
--
$ *podman image list | grep httpd-system*
localhost/httpd-system                            latest      8b0253366051  18 hours ago  1.56 GB
--

2. Publish the bootc container image in a private registry.

.. Copy your bootc container image to the registry and set a non-floating (or fixed) tag which includes a build number, so it remains unique as you perform more builds of the same image.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo copy containers-storage:localhost/httpd-system docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234*
...
Writing manifest to image destination
--

.. Copy a SSH public key to your _test machine_, so you can use it to access it after reboot. [ MAY NOT BE NEEDED ]
+
[source,subs="verbatim,quotes"]
--
$ *scp edge-key.pub servera:~*
edge-key.pub
--

3. Install the bootc utitily on your _test machine_, which in the classroom environment is the _servera_ machine.

.. Open an SSH session to your _test machine_. If you are using the classroom environment for this course, it uses the same `student` user as your _development machine_.
+
[source,subs="verbatim,quotes"]
--
$ *ssh servera*
--
+
NOTE: The classroom environment also enables you to open a web terminal direclty on the `servera` machine.

.. Install the bootc utility.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install bootc*
...
Complete!
--

.. Verify that your _test machine_ was created in the traditional way, using package mode for RHEL.
+
[source,subs="verbatim,quotes"]
--
$ *bootc status*
System is not deployed via bootc.
--

4. Re-install your _test machine_ from a bootc container image.

.. WHERE IS THE CA CERTIFICATE IN AN ALREADY BUILT CLASSROOM?

.. Install the public CA certificate of your private container registry, so you do NOT need to disable TLS validation when acessing its container images.
+
[source,subs="verbatim,quotes"]
--
$ *scp utility:/opt/registry/certs/domain.crt .*
domain.crt 
$ *sudo cp domain.crt /etc/pki/ca-trust/source/anchors/*
$ *sudo update-ca-trust extract*
--

.. Log in on your private registry.
Remember that the prevuous login was on your _developer machine_.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Verify that your _test machine_ has access to your private registry and can access the desired bootc container iamge
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman search registry.lab.example.com:5000/httpd-system*
NAME                                                  DESCRIPTION
registry.lab.example.com:5000/localhost/httpd-system
--
+
WARNING: The `podman search` and similar commands are NOT reliable ways to determine if a container image actually exists in a container registry.
Here it is used just as a convenience, but with most production private and public registries you must know the name and tag of a container image in advance, and use either `skopeo inspect` or `podman pull` to check for the existence of an image.

.. Log in again to your private container registry, to store registry credentials for the root user.
+
[source,subs="verbatim,quotes"]
--
$ sudo podman login -u student -p redhat registry.lab.example.com:5000
Login Succeeded!
--

.. Install the bootc container image, overriding the existem RHEL installation on the _test machine_.
+
Be sure you select both of the existing SSH keys, so you do not lose access to your _test machine_ after reboot.
+
[source,subs="verbatim,quotes"]
--
$ *sudo system-reinstall-bootc registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234*
Select which user's SSH authorized keys you want to
import into the root user of the new bootc system:
[*x*] root
[*x*] student
import into the root user of the new bootc system: root, student

Going to run command "podman" "run" "--privileged" "--pid=host" "--user=root:root" "-v" "/var/lib/containers:/var/lib/containers" "-v" "/dev:/dev" "--security-opt" "label=type:unconfined_t" "-v" "/:/target" "-v" "/tmp/.tmp04V3xX:/bootc_authorized_ssh_keys/root" "registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234" "bootc" "install" "to-existing-root" "--acknowledge-destructive" "--root-ssh-authorized-keys" "/bootc_authorized_ssh_keys/root"

THIS WILL REINSTALL YOUR SYSTEM! Are you sure you want to continue? [y/N]*y*
Trying to pull registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234...
...
ERROR Installing to filesystem: Verifying fetch: Creating importer: failed to invoke method OpenImage: failed to invoke method OpenImage: pinging container registry registry.lab.example.com:5000: Get "https://registry.lab.example.com:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
--

.. Previous command failed on TLS certificate validation... it's NOT mounting /etc/pki from the host into the privileged container. :-(

.. Being brave and using bootc install directly
+
[source,subs="verbatim,quotes"]
--
$ *sudo bootc install to-existing-root --source-imgref registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234*
ERROR Installing to filesystem: Verifying fetch: Creating importer: failed to invoke method OpenImage: failed to invoke method OpenImage: reading manifest v1.0-1234 in registry.lab.example.com:5000/localhost/httpd-system: authentication required
--

.. MUST FIND WHY THE TWO ATTEMPTS ABOVE FAILED
+
Add --skip-fetch-check to the command and not use the wrapper?
+
Looks like I MUST run bootc install from the booc container image itself, as a privileged container.
+
May also need -v /etc/pki:/etc/pki

.. Looks like it MUST BE run from a container, so trying again with a script.
+
[source,subs="verbatim,quotes"]
--
[student@servera ~]$ sudo bash bootc-instal.sh 
Installing image: docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234
Digest: sha256:0a64fe29217414a0cf68ae18c41997ff737e68aec52a96e44c25fcb7403476e2
----------------------------
WARNING: This operation will OVERWRITE THE BOOTED HOST ROOT FILESYSTEM and is NOT REVERSIBLE.
Waiting 20s to continue; interrupt (Control-C) to cancel.
----------------------------
ERROR Installing to filesystem: Verifying empty rootfs: Non-empty root filesystem; found "dev"
[student@servera ~]$ sudo bash bootc-instal.sh 
Installing image: docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234
Digest: sha256:0a64fe29217414a0cf68ae18c41997ff737e68aec52a96e44c25fcb7403476e2
Initializing ostree layout
layers already present: 0; layers needed: 71 (838.5 MB)
Deploying container image...done (35 seconds)
Running bootupctl to install bootloader
> bootupctl backend install --write-uuid --update-firmware --auto --device /dev/sda /target
Installed: grub.cfg
Installation complete!
[student@servera ~]$ sudo bootc status
[sudo] password for student: 
## Need a way of veryfying what was done BEFORE reboot. :-(
System is not deployed via bootc.
[student@servera ~]$ sudo systemctl reboot --now
## Boot messages look good, I see httpd and other stuff
## After reboot, I have no way of entering the system. No users, no SSH keys?!?!
## I hoped it would preserve some of the /etc of the original system
## couldn't login as student on the console
student@workstation:~$ ssh servera
ssh: connect to host servera port 22: No route to host
student@workstation:~$ ping -c1 servera
PING servera.lab.example.com (172.25.250.10) 56(84) bytes of data.
From workstation.lab.example.com (172.25.250.9) icmp_seq=1 Destination Host Unreachable
## Crap, I cannot reset servera to its original image. No snapshots on ROLE anymore?
## Is the problem a lack of a DHCP server to initialize the VM?
--

.. Add --root-ssh-authorized-keys and --kargs with network config? Would it be good adding --generic-image?
+
[source,subs="verbatim,quotes"]
--
# kargs: ip=172.25.250.11 netmask=255.255.255.0 gateway=172.25.250.0 (lightspeed)
# ip=172.25.250.11:255.255.255.0:172.25.250.0::ens3:off (google search AI)
# ip=<client-ip>:<server-ip>:<gw-ip>:<netmask>:<hostname>:<device>:<autoconf>:
   <dns0-ip>:<dns1-ip>:<ntp0-ip> (stack exchange)
# ip=172.25.250.11::172.25.250.0:255.255.255.0:bootc:ens3:off:172.25.250.220
[student@serverb ~]$ ip -br addr show
lo               UNKNOWN        127.0.0.1/8 ::1/128 
ens3             UP             172.25.250.11/24 fe80::5054:ff:fe00:fa0b/64 
ens4             UP             
[student@serverb ~]$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         classroom.lab.e 0.0.0.0         UG    100    0        0 ens3
172.25.250.0    0.0.0.0         255.255.255.0   U     100    0        0 ens3
[student@serverb ~]$ cat /etc/resolv.conf 
# Generated by NetworkManager
search lab.example.com example.com
nameserver 172.25.250.220
[student@serverb ~]$ nmcli device status
DEVICE  TYPE      STATE                                  CONNECTION         
ens3    ethernet  connected                              cloud-init ens3    
ens4    ethernet  connecting (getting IP configuration)  Wired connection 1 
lo      loopback  connected (externally)                 lo
[student@serverb ~]$ nmcli connection show
NAME                UUID                                  TYPE      DEVICE 
cloud-init ens3     fab1e257-61a6-3526-abf9-8c50c83a28c7  ethernet  ens3   
Wired connection 1  6ee7c93a-43e8-3afe-bfc8-f6a32916459b  ethernet  ens4   
lo                  6b429f96-be91-4a94-aed8-6b5b754f5c69  loopback  lo 
## only the first shows if adding --active
[student@serverb ~]$ nmcli -f ipv4.method connection show 'cloud-init ens3'
ipv4.method:                            manual
student@workstation:~/temp-test-vm$ scp edge-key.pub serverb:~
edge-key.pub 
student@workstation:~$ ping -q -c1 serverb
PING serverb.lab.example.com (172.25.250.11) 56(84) bytes of data.
## Using a pre-pulled image, no need to pass creds and CA roots to bootc install
## copy registry domain.crt to serverb, update-ca, sudo podman login and sudo pull

### Had a dump mistake on by bootc-install.sh and even if it works, it won't have the right SSH key.
### Will have to recreate the classroom
### Cannot try again before reboot. Do it right, or lose it
[student@serverb ~]$ sudo bash bootc-install.sh 
Installing image: docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234
Digest: sha256:0a64fe29217414a0cf68ae18c41997ff737e68aec52a96e44c25fcb7403476e2
Reusing extant ostree layout
ERROR Installing to filesystem: Creating ostree deployment: Cannot redeploy over extant stateroot default

### Previous attempt got a working instance (but locked down), last attempt cannot boot. Because of my --karg?
--

.. MAYBE I SHOULD DO IT IN A NESTED VM? OR HAVE A FALLBACK USER ON THE IMAGE?

5. Verify that the _test machine_ booted using the bootc container image.

.. TBD

6. Promote you bootc container image for use by actual edge devices.

.. Set a floating tag for the major.minor version number of your image.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo copy containers-storage:localhost/httpd-system docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0*
...
Copying blob 210b201289a0 skipped: already exists  
Copying blob ad312c5c40cc skipped: already exists  
---
Copying config 8f58cf789c done   | 
Writing manifest to image destination
--
+
Notice that the `skopeo copy` command above did NOT actually copied any layers, because all of them they already exist on the container registry, from the previous copy operation.

.. Also tag the same image as `latest` in the container registry.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo copy docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234 docker://registry.lab.example.com:5000/localhost/httpd-system:latest*
...
Copying blob 4b7b4242bfaa skipped: already exists  
Copying blob c7b030c219e8 skipped: already exists  
...
Copying config 8f58cf789c done   | 
Writing manifest to image destination
--
+
IMPORTANT: A CI/CD system would probaly use that style of copy, from remote to remote, to set all floating tags, instead of making multiple copies from local to remote, as you did in the previous step.
This activity uses both styles to demonstrate that it makes no different on the final result.

.. Verify that the three tags (one fixed, two floating) are listed in your bootc container image repository, and that the three tags possess the same digest, so they actually are alternate tags for exactly the same image.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo inspect --format '{{ json .RepoTags }}' docker://registry.lab.example.com:5000/localhost/httpd-system | jq*
[
  "latest",
  "v1.0",
  "v1.0-1234"
]
$ *skopeo inspect --format '{{ .Digest }}' docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0-1234*
sha256:0a64fe29217414a0cf68ae18c41997ff737e68aec52a96e44c25fcb7403476e2
$ *skopeo inspect --format '{{ .Digest }}' docker://registry.lab.example.com:5000/localhost/httpd-system:v1.0*
sha256:0a64fe29217414a0cf68ae18c41997ff737e68aec52a96e44c25fcb7403476e2
$ *skopeo inspect --format '{{ .Digest }}' docker://registry.lab.example.com:5000/localhost/httpd-system:latest*
sha256:0a64fe29217414a0cf68ae18c41997ff737e68aec52a96e44c25fcb7403476e2
--

////
Lab SSH key is at /etc/.rht_authorized_keys

[student@serverb ~]$ sudo cat /etc/.rht_authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAx/Xk+tLGBCatkBuxzyEXVhupSgb4Lema0PAnM8dFbSxcPz4W4jO8yQgtONzHs8KOhs4J1NG9bHeAwpJa2p9iJkyrigxmQv0LOpvENdlGbA1hwsRoOhBGqwRzSmKHS4Or94FBXvzDwHfbkxDV0XhzHKod8b9tYuaIQfhbF3NUR2ItZiYJhBds+3GOAHhdbU9DOAyX8X60vppkgoJ4nb2Mugw51LM+uVh8ds24wzU3Khr6Dcmae7KX/b/PX0J0rO23ZPq1AJ3i6r13AJUc6beLjQXPzYs/ZLKiQZWaZUePnsiaIpKXpH7vuBK3zidvcK2pf6XXAB9MW7GtoFJnr6v+bQ== InstructorKey
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGtUW3ismHyuCW4CDdTVOOOq6aySdtYenXFWWx7HJa4VTepkG00aaLId9ocra10hc+MB0GTJMCyabDv3i8NKdi6GDH/aOLVsp/Ewy8DEzZMBlJDCt4v2i4/wU4liw6KgEFkZs+5hnqU8d4QzldyGJ5onr+AGvFOKG68CS0BBl40Z1twf1HhCyx8k6nzD2ovlkxWRFZKPAFrtPCBVvQDkOfVFZF+lwzaSztgAjbFZ4A9jqQyUYx4kOJ5DtRef36ucdUdVQale0+8lICl7/gb142SPpYfhxe88/BJScLPRjvVNeu1TxRmoHtVazqnAoRxQYAn2MoI6AG+w6QuZf8f7aL LabGradingKey
[student@serverb ~]$ sudo grep Keys /etc/ssh/sshd_config 
AuthorizedKeysFile /etc/.rht_authorized_keys .ssh/authorized_keys
////

== What's Next

This was the final lab in this course, but the next course of this learning approach shows how to use the bootc image builder utility to create customized installation medias for edge devices and how to create customized boot disk images for clouds and hypervisors.