= Test Bootc Containers With Bootc Install

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Create containerfiles and build bootc container images for RHEL for edge systems

WARNING: Work in progress

== PROVISORY OUTLINE

* Use a preexisting VM (or create a new one using package mode) and use bootc install and/or system-reinstall-bootc to replace the OS on that VM with a bootc container image.
* Optional: use Podman Desktop (or just macadam) as a simpler way of testing bootc container images with local VMs, for the benefit of non-Linux developers
* Try to do it without a remote container registry. If it's too cumbersome, reorder topics so this lab and its presentation come the last in the course
* This lab is NOT trying to emulate provisioning physical devices using local VMs, but to boot a VM from a bootc container image the quickest/simplest way possible, for inner loop testing of new images.


== Before you Begin

You need a _development machine_ running RHEL, to which you have access using an unprivileged user account.

These instructions were tested on RHEL 10.0 but should work with minimal or no change on and newer and older RHEL releases, since 9.6.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`. If not, please adapt the instructions to your test environment.

Make sure you verified your test environment by following the xref:ch1-intro:s3-prereqs-lab.adoc[first lab] of this course.

== Instructions

1. Prepare to start this activity by checking that you have the outcomes from previous activities.

.. If needed, create a local clone of the sample code repository of this course, and make it your working directory.
+
[source,subs="verbatim,quotes"]
--
$ *git clone https://github.com/RedHatQuickCourses/rhde-bootc-samples.git*
Cloning into 'rhde-bootc-samples'...
...
$ *cd rhde-bootc-samples*
--

.. If needed, login to your private registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Verify that you have bootc container images named AAA and BBB.
If you do not, please perform the xref:ch2-build:s2-podman-lab.adoc[previous labs].
+
[source,subs="verbatim,quotes"]
--
$ *podman image list*
GRAB OUTPUT
--

2. Create a local virtual machine (VM), using the libvirt tools, that you can use to install your bootc container images..

.. Try a command that installs RHEL unattended, from a kickstart file.
+
[source,subs="verbatim,quotes"]
--
### SCRATCHPAD FOR TESTING COMMANDS
$ cd # run from $HOME
$ mkdir temp-bootc
$ skopeo copy containers-storage:localhost/http-bootc oci:temp-bootc:http-bootc
$ virt-install
--

.. Alternativelly, try a RHEL cloud image (which I would have to add to the HOL019 classroom).
+
[source,subs="verbatim,quotes"]
--
### SCRATCHPAD FOR TESTING COMMANDS
$ *virt-istall*
--

== What's Next

The next chapter demonstrates how to publish bootc container images on OCI container registries, so they can be used to provision physical systems, cloud instances, or virtual machines on the data center.