:time_estimate: 5

= Lab: System Configuration From Containers

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Create containerfiles which include system configurations and demonstrate that they cannot be effectively tested using Podman.

WARNING: Not Started

== PROVISORY OUTLINE

* If I cannot get a good and not too complex example of a Containerfile with “advanced” features, skip this lab and have a shorter presentation.
* Maybe a multistage build using ansible system roles to preconfigure a system?
* Ideally, one example that “works” on podman, and another that doesn’t, to reinforce the need to test by provisioning actual systems or VMs.
* Leave “from scratch” images for a follow-up course, as an advanced topic that learners should try only after they master more of image mode, including the two following courses.

== Before you Begin

You need a _development machine_ running RHEL, to which you have unrestricted sudo rights and also access to RHEL package repositories.
That machine must have plenty of disk space to store multiple container images and multiple Virtual Machine (VM) images.

These instructions were tested on RHEL 10.0 but should work with minimal or no change on and newer and older RHEL releases, since 9.6.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`. If not, please adapt the instructions to your test environment.

== Instructions

1. Prepare to start this activity by checking that you have the outcomes from previous activities.

.. If needed, create a local clone of the sample code repository of this course, and make it your working directory.
+
[source,subs="verbatim,quotes"]
--
$ *git clone https://github.com/RedHatQuickCourses/rhde-bootc-samples.git*
Cloning into 'rhde-bootc-samples'...
...
$ *cd rhde-bootc-samples*
--

.. If needed, login to your private registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

== What's next

The next chapter demonstrates how to test your bootc container images from a local VM, so you can validate settings that you cannot with Podman.